export const properties = [
  {
    id: 1,
    title: "Luxurious Beachfront Villa",
    location: "Boracay, Philippines",
    max_capacity: 10,
    num_bedrooms: 5,
    num_bathrooms: 5,
    price_per_night_php: 15000,
  },
  {
    id: 2,
    title: "Cozy Mountain Cabin",
    location: "Baguio City, Philippines",
    max_capacity: 6,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 8000,
  },
  {
    id: 3,
    title: "City View Penthouse",
    location: "Manila, Philippines",
    max_capacity: 8,
    num_bedrooms: 4,
    num_bathrooms: 3,
    price_per_night_php: 12000,
  },
  {
    id: 4,
    title: "Rustic Countryside Cottage",
    location: "Tagaytay, Philippines",
    max_capacity: 4,
    num_bedrooms: 2,
    num_bathrooms: 1,
    price_per_night_php: 5000,
  },
  {
    id: 5,
    title: "Modern City Apartment",
    location: "Quezon City, Philippines",
    max_capacity: 3,
    num_bedrooms: 1,
    num_bathrooms: 1,
    price_per_night_php: 4000,
  },
  {
    id: 6,
    title: "Seaside Bungalow",
    location: "Puerto Galera, Philippines",
    max_capacity: 6,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 7000,
  },
  {
    id: 7,
    title: "Historic District Townhouse",
    location: "Vigan, Philippines",
    max_capacity: 5,
    num_bedrooms: 2,
    num_bathrooms: 2,
    price_per_night_php: 6000,
  },
  {
    id: 8,
    title: "Mountain View Chalet",
    location: "Sagada, Philippines",
    max_capacity: 7,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 9000,
  },
  {
    id: 9,
    title: "Island Retreat",
    location: "Palawan, Philippines",
    max_capacity: 12,
    num_bedrooms: 6,
    num_bathrooms: 4,
    price_per_night_php: 18000,
  },
  {
    id: 10,
    title: "Eco-Friendly Treehouse",
    location: "Davao City, Philippines",
    max_capacity: 2,
    num_bedrooms: 1,
    num_bathrooms: 1,
    price_per_night_php: 3000,
  },
  {
    id: 11,
    title: "Artistic Loft",
    location: "Cebu City, Philippines",
    max_capacity: 4,
    num_bedrooms: 2,
    num_bathrooms: 1,
    price_per_night_php: 5500,
  },
  {
    id: 12,
    title: "Sunny Coastal Cottage",
    location: "Zambales, Philippines",
    max_capacity: 5,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 6500,
  },
  {
    id: 13,
    title: "Lakefront Cabin",
    location: "Laguna, Philippines",
    max_capacity: 8,
    num_bedrooms: 4,
    num_bathrooms: 3,
    price_per_night_php: 10000,
  },
  {
    id: 14,
    title: "Charming Village House",
    location: "Ilocos Norte, Philippines",
    max_capacity: 6,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 7500,
  },
  {
    id: 15,
    title: "Tropical Paradise Resort",
    location: "Cagayan de Oro, Philippines",
    max_capacity: 10,
    num_bedrooms: 5,
    num_bathrooms: 5,
    price_per_night_php: 16000,
  },
  {
    id: 16,
    title: "Sleek Urban Condo",
    location: "Mandaluyong City, Philippines",
    max_capacity: 2,
    num_bedrooms: 1,
    num_bathrooms: 1,
    price_per_night_php: 3500,
  },
  {
    id: 17,
    title: "Beachside Resort Suite",
    location: "Subic Bay, Philippines",
    max_capacity: 4,
    num_bedrooms: 2,
    num_bathrooms: 1,
    price_per_night_php: 6000,
  },
  {
    id: 18,
    title: "Traditional Nipa Hut",
    location: "Pampanga, Philippines",
    max_capacity: 3,
    num_bedrooms: 1,
    num_bathrooms: 1,
    price_per_night_php: 2500,
  },
  {
    id: 19,
    title: "Scenic Riverfront House",
    location: "Iloilo City, Philippines",
    max_capacity: 8,
    num_bedrooms: 4,
    num_bathrooms: 3,
    price_per_night_php: 11000,
  },
  {
    id: 20,
    title: "Mountain Retreat",
    location: "Benguet, Philippines",
    max_capacity: 6,
    num_bedrooms: 3,
    num_bathrooms: 2,
    price_per_night_php: 8500,
  },
];
